# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock README.md ./
COPY src ./src

# Install dependencies
RUN pip install --no-cache-dir .

# Expose port if needed (MCP uses stdio, no port)

# Default command to start the MCP server
CMD ["python", "src/main.py"]
